sudo: required
dist: trusty

language: node_js

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          node_js: 6
        - os: osx
          node_js: 6

addons:
    apt:
        packages:
            - libgnome-keyring-dev
            - icnsutils
            - graphicsmagick
            - xz-utils
            - rpm
            - bsdtar

install:
    - npm install

script:
    - ./build/script/travis-build.sh

deploy:
    - provider: releases
      api_key:
        secure: o961hrUtOURo8uSzskTxgdg3W7ORvP3Wri2cp7ptcu4Jj/L2PgK/j052UkrZGKEvvQj2e11MEOMO/NYvF0BXzI7aRkyS5RdW5QDojVrQ1emN6Kyi9jl+X6q+klG1r+W1Clb4q6w+pZ5k5B2L2I5KUuYd0H5b8z2YV5tQagM3A7/VuDvdInybsiJqXJukYmxjmwClTNFzg0CUYGgiRwG4MsNC+1uxBjP5Jn2BBqpMXV4J6ofXvC0qbyxwcKFOl3Nxc0NQstaKqKvjYH8aFEAVymiEXQF4sYhTVBMdfg54ChsORZVj3/mYivRnB3g+4Na1JFjg4uooNKK4WTa8TrGmXvOS7YxWlF+A2HvvgU5C7tw3QPBS73kbjzq7UcsTpY1qOJHbVH4lkwnQzOVayWZfF/PgutXDxOLLtiZgZt9zCob1eJNxoTqdQAWLoXY3OqWE7aaADD0vDaTi6SklJOKuB1F0AemNdi1Xjmwfw7OfJFpzYu1V5LU1OSOgVZQoZ1OznW2Vr0xiNe14MB+odghzV2fT1PjfXsj++pOhnwNOUNh1dvJrehAKCiv5nhJlbkoUmuqnXNTOGPzz24UzqT+GO5mueNvnpYFhRC9HzyeOtntB8oiB6Jc2hHaY7TIP5djOxgTgxTD7DSKHsWHawrIltgwWNwAbR7VgMvQKu1rqBgY=
      file_glob: true
      file:
        - dist/*.dmg
        - dist/mac/*.zip
      skip_cleanup: true
      on:
        condition: $TRAVIS_OS_NAME = osx
        tags: true
        repo: extr0py/oni
    - provider: releases
      api_key:
        secure: o961hrUtOURo8uSzskTxgdg3W7ORvP3Wri2cp7ptcu4Jj/L2PgK/j052UkrZGKEvvQj2e11MEOMO/NYvF0BXzI7aRkyS5RdW5QDojVrQ1emN6Kyi9jl+X6q+klG1r+W1Clb4q6w+pZ5k5B2L2I5KUuYd0H5b8z2YV5tQagM3A7/VuDvdInybsiJqXJukYmxjmwClTNFzg0CUYGgiRwG4MsNC+1uxBjP5Jn2BBqpMXV4J6ofXvC0qbyxwcKFOl3Nxc0NQstaKqKvjYH8aFEAVymiEXQF4sYhTVBMdfg54ChsORZVj3/mYivRnB3g+4Na1JFjg4uooNKK4WTa8TrGmXvOS7YxWlF+A2HvvgU5C7tw3QPBS73kbjzq7UcsTpY1qOJHbVH4lkwnQzOVayWZfF/PgutXDxOLLtiZgZt9zCob1eJNxoTqdQAWLoXY3OqWE7aaADD0vDaTi6SklJOKuB1F0AemNdi1Xjmwfw7OfJFpzYu1V5LU1OSOgVZQoZ1OznW2Vr0xiNe14MB+odghzV2fT1PjfXsj++pOhnwNOUNh1dvJrehAKCiv5nhJlbkoUmuqnXNTOGPzz24UzqT+GO5mueNvnpYFhRC9HzyeOtntB8oiB6Jc2hHaY7TIP5djOxgTgxTD7DSKHsWHawrIltgwWNwAbR7VgMvQKu1rqBgY=
      file_glob: true
      file:
          - dist/*.deb
          - dist/*.rpm
          - dist/*.tar.gz
      skip_cleanup: true
      on:
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        repo: extr0py/oni
