sudo: required
dist: trusty
language: node_js
branches:
  only:
  - master
  - /^release.*/
cache:
    yarn: true
    directories:
        - node_modules
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    node_js: 8
  - os: osx
    node_js: 8
addons:
  apt:
    packages:
    - libxkbfile-dev
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
install:
- npm install -g yarn
- yarn install
script:
- ./build/script/travis-build.sh
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/coveralls < coverage/lcov.info; fi
deploy:
    - provider: s3
      access_key_id: AKIAIPVCKNWKWB2XULQQ
      secret_access_key:
        secure: IKLeZsM1R8pq/eBqBCnsFe6iSF+ZHaokY6yBf6FtxaqHw7qJR3RQ9XI9N7mooKXOAsp7prDBNW6sdciGmzXpDW7myDz5eEfmVOIZxb6zq0XUwsikkgrzgS22bMkj32CZuRzR8agzF7US+G6OfVo+MIhChOPKBfqkbUbQdWm0tYX0NJsNyt8Ax8GdyzAj98cazw5tV2HWT7M11EKQCssc1CiFWqR51Zqmy34d/jEWJEe+P3avRDpNCJf6uuzfrtpn1swCb0EY7aZGDischXwRJDyZ6GXrjECxazN2T7JwcwKw/Y+XOeiwp5H+ell+1C/tZMXcn8OyOZurVQdG7MNGHil0Jt/t4QL6XpNXXF8I1k1LQDty7SPnZRKaAYo8rNyDFqGt5oVLvTm8GD9KjI4rGPt7VvzUQS5SITRnI1m6wq0YDdVqcR9/Z2cLmXHmzhOmB3FLCTKQXXCMaG1dAzlYQDOspo9RKr+nuDpherNMSiqSeVUM97UrfRQ2pC/JfoL/f6j2jt88Y7XfF9x48h+6Pm8ny5rlSaU4otnVpgAeoMEMED5s93zZrVxF7ydyZ0ZvBLKfK13mJwleCq3R1DbYStp1bor0MFwVoVRRRLcxIo6bhlmJsd0qhIFXL8BcE1wLzDITnXVxAxg9izRPYPcSgRLyjJ1SqaxoT89cO0YlNEU=
      bucket: oni-media
      local-dir: dist/media
      acl: public_read
      region: us-west-2
      skip_cleanup: true
      on:
        condition: $TRAVIS_OS_NAME = osx
        repo: onivim/oni
    - provider: releases
      api_key:
        secure: AjQUeQNockqkBrVQCOQGyKq+sZ9C4SabSqp/bmXayKTB+7AmM8oohenxC09Sc4/dmIW1PQnDYL/4fjclJSRaywV5oiPqUnfhTveALkKFErmYnhA8oFi3VJYg4Tbszb2lYGITLOluuuAZGw67JZIuuiXzw/yOUfdWTmRCAVGzTmqkPsusYg56L4iRBWDwYQ3mhHsuNKFO7SIx1nJatj5hK9AkDJlcVilpA5IuWLWOHLY7nplFPUPUwMkRd99nifB7ITycbaAX4zLwp2U2wCb2uSTOzsFNfXykksf8AlreH0615Jb+T39/dDwQurDAQE3h+KUH5QhEvRJ1uphkGvx/x6Vn0LkJuSqS5DLeSATmVOVRK2f6AXcymvn/64qxizjlBR7bBoUxM55311qWJNKKk2FYFTAIW5fMzN0MRbaulpnpBwmhnBvd03rOMIghnvClHv2m8Eh5A6ppPnLcl2Vn7jsrqTmMm+PM1ppIWhCpvC7xn4digx1GGHXlYzfHkDxtnHwHcbj+WOkc+j4ha8Os+1ctdT3OJXz5rwW4viorSIhWryK+G36beguXe5YaoeMcK9Vzmb+S0lHdA7RuCWiJ31i/9ZMbzBhLkdcf/wfj9n3mkqmzvc4Uc1NM8FHQ23URsodSHpTdDi7q25Eqge/JP82AqJ2zAWA+QKVg54xCQQc=
      file_glob: true
      file:
        - dist/*.dmg
        - dist/*.zip
      skip_cleanup: true
      on:
        condition: $TRAVIS_OS_NAME = osx
        tags: true
        repo: onivim/oni
    - provider: releases
      api_key:
        secure: AjQUeQNockqkBrVQCOQGyKq+sZ9C4SabSqp/bmXayKTB+7AmM8oohenxC09Sc4/dmIW1PQnDYL/4fjclJSRaywV5oiPqUnfhTveALkKFErmYnhA8oFi3VJYg4Tbszb2lYGITLOluuuAZGw67JZIuuiXzw/yOUfdWTmRCAVGzTmqkPsusYg56L4iRBWDwYQ3mhHsuNKFO7SIx1nJatj5hK9AkDJlcVilpA5IuWLWOHLY7nplFPUPUwMkRd99nifB7ITycbaAX4zLwp2U2wCb2uSTOzsFNfXykksf8AlreH0615Jb+T39/dDwQurDAQE3h+KUH5QhEvRJ1uphkGvx/x6Vn0LkJuSqS5DLeSATmVOVRK2f6AXcymvn/64qxizjlBR7bBoUxM55311qWJNKKk2FYFTAIW5fMzN0MRbaulpnpBwmhnBvd03rOMIghnvClHv2m8Eh5A6ppPnLcl2Vn7jsrqTmMm+PM1ppIWhCpvC7xn4digx1GGHXlYzfHkDxtnHwHcbj+WOkc+j4ha8Os+1ctdT3OJXz5rwW4viorSIhWryK+G36beguXe5YaoeMcK9Vzmb+S0lHdA7RuCWiJ31i/9ZMbzBhLkdcf/wfj9n3mkqmzvc4Uc1NM8FHQ23URsodSHpTdDi7q25Eqge/JP82AqJ2zAWA+QKVg54xCQQc=
      file_glob: true
      file:
          - dist/*.deb
          - dist/*.rpm
          - dist/*.tar.gz
      skip_cleanup: true
      on:
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        repo: onivim/oni
